{% set name = "rill" %}
{% set version = "0.40.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/rilldata/rill/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 67f36298d5f83f89cf0cee9a982d56e7637fd8ef70e666f295fa709456db35ea
  - url: https://gitlab.com/cznic/mathutil/-/raw/b13e5b5643328f15fd2fcedc85f647f0d8f9180f/LICENSE  # v1.5.0
    sha256: bfa9bf72a72ca009fd62a8f84fca3dca67e51d93af96352723646599898b6cf5
    fn: LICENSE-mathutil
  - url: https://raw.githubusercontent.com/uber-go/zap/56468e797f1dbf3905ad7c34b5513928206244bf/LICENSE.txt  # v1.25.0
    sha256: 7de716e70addb64f9305298ef32a9dd68e40d5b3095a5d868ba4461404dbfbcf
    fn: LICENSE-zap

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('go-cgo') }}
    - {{ compiler('cxx') }}
    - go-licenses
    - nodejs =18
    - make
    - pkg-config  # [osx]
  host:
    - librdkafka
    - libduckdb
    - zlib
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - test -f $PREFIX/bin/rill

about:
  home: https://github.com/rilldata/rill
  summary: Rill is a tool for effortlessly transforming data sets into powerful, opinionated dashboards using SQL. BI-as-code.
  license: Apache-2.0
  license_file:
    - LICENSE.md
    - LICENSE-mathutil
    - LICENSE-zap
    - library_licenses/
  doc_url: https://docs.rilldata.com/
  dev_url: https://github.com/rilldata/rill

extra:
  recipe-maintainers:
    - janjagusch
